name       : plib
version    : 1.8.5
release    : 1
source     :
    - http://plib.sourceforge.net/dist/plib-1.8.5.tar.gz : 485b22bf6fdc0da067e34ead5e26f002b76326f6371e2ae006415dea6a380a32
license    : GPL-2.0
component  : programming
summary    : A Suite of Portable Game Libraries
description: |
    A Suite of Portable Game Libraries
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(x11)
setup      : |
    # Disable glNewList check
    sed -i "291,295d" configure.in
    %autogen --disable-ssg --disable-ssgaux
build      : |
    %make
install    : |
    %make_install
